name: echo # On donne un titre à notre Workflow
# On indique a github quand le déclencher
# Est ce qu'on le déclenche au push, pull request, merge, push sur la branche ""
on: push
# On déclare des processus de travail
jobs:
# On donne un nom à nos jobs
  Tests:
    runs-on: ubuntu-latest
  # On declare les tâches que notre processus va executer
    steps:
      - name: "echo"
        run: echo "je fais des tests"
